"""
Parse all saved LL season home pages in 'LL Season Home Pages/' and write pct.js.
Run once from this directory to regenerate the static % correct data.
"""
import re, json, os, glob

def parse_season_file(html_text):
    lookup = {}

    # Season number from <h1 class='matchday'> or class="matchday"
    h1_match = re.search(r"<h1[^>]*class=['\"]matchday['\"][^>]*>(.*?)</h1>", html_text, re.DOTALL)
    if not h1_match:
        return lookup
    season_match = re.search(r'LL(\d+)', h1_match.group(1))
    if not season_match:
        return lookup
    season = int(season_match.group(1))

    # Find all table rows containing match.php links for this season
    # Rows are <tr>...</tr>; we only care about ones with enough <td> cells
    row_re  = re.compile(r'<tr[^>]*>(.*?)</tr>', re.DOTALL)
    cell_re = re.compile(r'<td([^>]*)>(.*?)</td>', re.DOTALL)

    for row_m in row_re.finditer(html_text):
        row_html = row_m.group(1)
        cells = list(cell_re.finditer(row_html))
        if len(cells) < 12:
            continue

        # First cell must contain a match.php link for this season: /match.php?107&1&Rundle
        first_cell = cells[0].group(2)
        md_m = re.search(rf'/match\.php\?{season}&(\d+)', first_cell)
        if not md_m:
            continue
        md = int(md_m.group(1))

        # Q1–Q6 are at cell indices 6–11 (0-indexed), i.e. cells[5+q] for q=1..6
        for q in range(1, 7):
            idx = 5 + q
            if idx >= len(cells):
                continue
            cell_attrs   = cells[idx].group(1)
            cell_content = cells[idx].group(2)

            # Primary: CSS class q{pct} on the <td>
            cls_m = re.search(r"class=['\"]([^'\"]*)['\"]", cell_attrs)
            if cls_m:
                pct_m = re.search(r'\bq(\d+)\b', cls_m.group(1))
                if pct_m:
                    lookup[f'{season}-{md}-{q}'] = int(pct_m.group(1))
                    continue

            # Fallback: link text inside the cell
            link_m = re.search(r'<a[^>]*>(\d+)</a>', cell_content)
            if link_m:
                lookup[f'{season}-{md}-{q}'] = int(link_m.group(1))

    return lookup


folder = 'LL Season Home Pages'
combined = {}

for fpath in sorted(glob.glob(os.path.join(folder, '*.html'))):
    with open(fpath, encoding='utf-8', errors='replace') as f:
        html = f.read()
    result = parse_season_file(html)
    print(f'{os.path.basename(fpath)}: {len(result)} entries')
    combined.update(result)

print(f'\nTotal: {len(combined)} entries')

out_path = 'pct.js'
with open(out_path, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by _build_pct.py — do not edit manually\n')
    f.write('const LL_PCT = ')
    f.write(json.dumps(combined, separators=(',', ':')))
    f.write(';\n')

print(f'Written to {out_path}')
